### ISSUE TITLE
Functionality on AWS?

### ISSUE THREAD

**Issue by ktravis213** [nasa/earthdata-download#52]
Hi Earthdata download developers! This tool is great, and I am using it on my desktop.  I also have an account on the Science Managed Cloud Environment run by NASA, which is a Jupyterhub environment on Kubernetes. Is there a way to incorporate this tool into our cloud environment?

**Comment by macrouch** [comment]
Hi @ktravis213. Unfortunately, I don't think Earthdata Download is going to help within a cloud environment. This application was designed to fit the need of users downloading data directly to their workstations, not those working with cloud hosted data.

I'm not sure I totally understand your question though, and I'm happy to chat with you more about it if you'd like.
